[project]
name = "undervisning"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Torben Lauritzen", email = "tl@magus.dk" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
undervisning = "undervisning:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
